### ISSUE TITLE
Links to external sites etc.

### ISSUE THREAD

**Issue by gkapkowski** [Userfeeds/cryptopurr#26] opened 2018-04-20 06:34 UTC
Add:
- Links to cryptobeep, cryptomoji
- "Fork me on github" stripe (standard from github)
- Links to telegram and gitter

**Comment by michalwarda** [comment] 2018-04-20 07:26
This is a duplicate of: https://github.com/Userfeeds/cryptopurr/issues/9 . I'll change the title of that one.

**Closed by michalwarda** 2018-04-20 07:26 UTC
